image: hashicorp/terraform:full
pipelines:
    branches:
        develop:
            - step:
                deployment: dev
                script:
                    - cd environment/dev
                    - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
                    - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
                    - terraform init
                    - terraform validate
                    - terraform workspace select dev
                    - terraform plan -var 'env=dev'
                    - terraform apply -var 'env=dev' -input=false -auto-approve
        release/1.0:
            - step:
                deployment: release
                script:
                    - cd environment/dev
                    - export AWS_ACCESS_KEY_ID=$PRD_AWS_ACCESS_KEY_ID
                    - export AWS_SECRET_ACCESS_KEY=$PRD_AWS_SECRET_ACCESS_KEY
                    - terraform init
                    - terraform validate
                    - terraform workspace select prod
                    - terraform plan -var 'env=prod'
        main:
            - step:
                deployment: prod
                script:
                    - cd environment/dev
                    - export AWS_ACCESS_KEY_ID=$PRD_AWS_ACCESS_KEY_ID
                    - export AWS_SECRET_ACCESS_KEY=$PRD_AWS_SECRET_ACCESS_KEY
                    - terraform init
                    - terraform validate
                    - terraform workspace select prod
                    - terraform plan -var 'env=prod'
                    - terraform apply -var 'env=prod' -input=false -auto-approve

